[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "always"

[[services]]
name = "habit-tracker"

[services.source]
dockerfile = "Dockerfile"

[[services]]
name = "postgres"
serviceType = "database"

[services.database]
engine = "postgresql"